### ISSUE TITLE
LV2 build target/release?

### ISSUE THREAD

**Issue by mxmilkiib** [enter-opy/sound-of-music#8]
Hi! I was just wondering if an LV2 release might be a possibility some day? Thanks!

**Comment by enter-opy** [comment]
Thanks for your interest! I've compiled the LV2 release files into a zip file. Since I'm not very familiar with LV2, I was wondering if you could help test it and let me know if everything seems in order for a release.
[Sound of music.lv2.zip](https://github.com/enter-opy/sound-of-music/files/13402444/Sound.of.music.lv2.zip)

**Comment by mxmilkiib** [comment]
Oops, wrong button in a GitHub client!

Thank you v much! I'll check on linuxmusicians.com if anyone can test. My favourite host is Carla, but I'm not in a testing n packaging phase atm, more into advocacy n asking JUCE devs to turn LV2 builds on atm. LV2 is multiplatform so you could find a host easily enough (or grab some desktop Linux VM).

The plugin sound awesome though 😃
